name: Version

on:
  push:
    branches: ["main"]

jobs:
  semantic-release:
      runs-on: ubuntu-18.04
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
    - name: Create Version
      uses: caos/semantic-release@v1.0.0
    - name: Check if Version Tag is available
      if: env.CAOS_NEXT_VERSION == ''
      run: exit 1
